# Generated by Django 4.2.6 on 2023-10-27 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emissionsAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emissions',
            new_name='Emission',
        ),
    ]
